set_property SRC_FILE_INFO {cfile:D:/Projects/FPGA/lab62/lab62.srcs/constrs_1/new/const.xdc rfile:../../../lab62.srcs/constrs_1/new/const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports dout]
